# 默认 DaoCloud Hub 镜像；海外构建可：--build-arg DOCKER_HUB_PREFIX=docker.io/library
ARG DOCKER_HUB_PREFIX=docker.m.daocloud.io/library
FROM ${DOCKER_HUB_PREFIX}/node:20-alpine AS build
WORKDIR /app
COPY frontend/package.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

FROM ${DOCKER_HUB_PREFIX}/nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
